eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

microservice:
  movie-service:
    endpoints:
      endpoint:
        uri: http://movie-info-service/movies
  ratings-service:
    endpoints:
      endpoint:
        uri: http://ratings-data-service/ratings
