
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory-service
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        use-new-id-generator-mappings: false
    hibernate:
      ddl-auto: none
    show-sql: true
