
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory-service
    username: root
    password: root
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
