
spring:
  datasource:
    url: jdbc:mysql://inventory-service-mysql:3300/inventory-service
    password: P@ssw0rd

  rabbitmq:
    host: rabbitmq-0.rabbitmq

  zipkin:
    base-url: http://zipkin-0.zipkin:9411
      
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@discovery-service-0.discovery-service:8761/eureka
