server:
  port: 0
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory-service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

  # kafka configuration properties
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: productCreatedNotificationTopic
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: productCreatedEvent:com.moh.yehia.inventoryservice.model.response.ProductCreatedEvent
            trusted:
              packages: "*"
      group-id: productCreatedNotificationId
      
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true      

# actuator prometheus endpoint
management:
  endpoints:
    web:
      exposure:
        include: "prometheus"