
server:
  port: 0
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://inventory-service:3306/inventory-service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      probability: 1.0
      
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@eureka:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true  
