spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 9802

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# actuator prometheus endpoint
management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
