
spring:
  data:
    mongodb:
      uri: mongodb://product-service-mongo:27017/product-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}
    prefer-ip-address: true

server:
  port: 9804
  servlet:
    context-path: /product-service

# actuator prometheus endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"