
spring:
  data:
    mongodb:
      uri: mongodb://product-service-mongo:27017/product-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

  # kafka properties
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: productCreatedNotificationTopic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: productCreatedEvent:com.moh.yehia.productservice.model.response.ProductCreatedEvent
      
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}
    prefer-ip-address: true

server:
  port: 0
  servlet:
    context-path: /product-service

# actuator prometheus endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"