
spring:
  data:
    mongodb:
      uri: mongodb://product-service-mongo:27017/product-service
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@discovery-server:8761/eureka/